server:
  port: 8081
#  tomcat:
#    connection-timeout: 60s

spring:
  application:
    name: storage-service
  profiles:
    active: dev
  config:
    import: "optional:nacos:${spring.application.name}.yml?refresh=true,optional:nacos:${spring.application.name}-${spring.profiles.active}.yml?refresh=true"

  cloud:
    # Nacos帮助文档: https://nacos.io/zh-cn/docs/v2/concepts.html
    nacos:
      config:
        server-addr: mrcode.cn:8848
        namespace: "seata-server"
        group: SEATA_GROUP
        # 认证信息
        #        username: nacos
        #        password: nacos
        fileExtension: yaml
        import-check:
          enabled: false
      discovery:
        server-addr: mrcode.cn:8848
        # 注册到 nacos 的指定 namespace，默认为 public
        namespace: "seata-server"
        group: SEATA_GROUP
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://mrcode.cn:3306/dt_demo_b?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456


mybatis-plus:
  mapper-locations: classpath*:/repo/mapper/*Mapper.xml

debug: true


seata:
  enabled: true
  tx-service-group: default_tx_group  # 事务组名称
  registry:
    type: nacos  # 使用 Nacos 注册中心
    nacos:
      server-addr: mrcode.cn:8848
      namespace: "seata-server"
      group: SEATA_GROUP
      cluster: default
  service:
    vgroup-mapping:
      # no available service found in cluster 'default', please make sure registry config correct and keep your seata server running
      default_tx_group: default
  config:
    type: nacos
    nacos:
      data-id: seataServer.properties
      group: SEATA_GROUP
      namespace: "seata-server"
      server-addr: mrcode.cn:8848